<a href="https://colab.research.google.com/github/udaysharma1501/mlops_proj1/blob/main/pipeline1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install "zenml[server]"
!zenml integration install sklearn -y
%pip install pyparsing

import IPython

IPython.Application.instance().kernel.do_shutdown(restart=True)

⠏ Installing integrations...


{'status': 'ok', 'restart': True}

In [1]:
ngrock_authtoken = "2sPSTRBlZN2EokGq13FMrlrvITr_SmdhSuRZFureCs8MGyuY"

In [2]:
!rm -rf .zen
!zenml init

Initializing the ZenML global configuration version to 0.73.0
⠋ Initializing ZenML repository at /content.
Creating database tables
⠙ Initializing ZenML repository at /content.
⠹ Initializing ZenML repository at /content.
⠸ Initializing ZenML repository at /content.
⠼ Initializing ZenML repository at /content.
⠴ Initializing ZenML repository at /content.
⠦ Initializing ZenML repository at /content.
⠧ Initializing ZenML repository at /content.
⠇ Initializing ZenML repository at /content.
⠏ Initializing ZenML repository at /content.
⠋ Initializing ZenML repository at /content.
⠙ Initializing ZenML repository at /content.
⠹ Initializing ZenML repository at /content.
⠸ Initializing ZenML repository at /content.
⠼ Initializing ZenML repository at /content.
⠴ Initializing ZenML repository at /content.
⠦ Initializing ZenML repository at /content.
⠧ Initializing ZenML repository at /content.
⠇ Initializing ZenML repository at /content.
⠋ Initializing ZenML repository at /content.
⠙ Initializin

In [5]:
import numpy as np
from sklearn.base import ClassifierMixin
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler  # Import scaler
from sklearn.metrics import classification_report, confusion_matrix  # Import metrics

def train_test() -> None:
    """Train and test a Scikit-learn SVC classifier on digits with improvements"""

    digits = load_digits()
    data = digits.images.reshape((len(digits.images), -1))

    # Scale the data
    scaler = StandardScaler()
    data = scaler.fit_transform(data)

    X_train, X_test, y_train, y_test = train_test_split(
        data, digits.target, test_size=0.2, shuffle=True  # Shuffle is True
    )

    model = SVC(gamma='scale')  # 'scale' sets gamma automatically based on data
    model.fit(X_train, y_train)

    test_acc = model.score(X_test, y_test)
    print(f"Test accuracy: {test_acc*100}%")

    # More detailed evaluation
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

train_test()

Test accuracy: 97.77777777777777%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      0.98      0.99        42
           2       1.00      1.00      1.00        40
           3       1.00      0.97      0.99        35
           4       0.94      0.92      0.93        36
           5       1.00      1.00      1.00        33
           6       1.00      1.00      1.00        38
           7       0.97      0.94      0.96        35
           8       0.89      1.00      0.94        34
           9       0.97      0.97      0.97        38

    accuracy                           0.98       360
   macro avg       0.98      0.98      0.98       360
weighted avg       0.98      0.98      0.98       360

[[29  0  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  1  0  0  0  0  0]
 [ 0  0 40  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  1  0]
 [ 0  0  0  0 33  0  0  1  2  0]
 [ 0  0  0  0  0 33  0  0  0  0]
 [ 0  0  